#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
export LOG=/home/kas/leftwm-theme.log

echo "Calling up" >> $LOG;

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

echo "Linked new down script" >> $LOG;

#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
  echo "Booting compton" >> $LOG;
  compton &> /dev/null & 
elif [ -x "$(command -v picom)" ]; then
  echo "Booting picom" >> $LOG;
  picom &> /dev/null & 
fi

# Start the KDE polkit agent
systemctl --user start plasma-polkit-agent

#set the theme.toml config
echo "Setting theme.toml config" >> $LOG;
echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/command-0.pipe
# leftwm command "LoadTheme /home/kas/.config/leftwm/themes/current/theme.toml"


#set background
echo "Setting background to $SCRIPTPATH/background.png" >> $LOG;
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/background.png
fi


index=0
monitors="$(polybar -m | sed s/:.*//)"
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  let indextemp=index+1
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c $SCRIPTPATH/polybar.config $barname &> /dev/null &
  let index=indextemp
done
