function cleanuphome
    if [ -d node_modules ];
        rm -rf node_modules;
    end;
    if [ -d vscode ];
        cd vscode;
        if [ -d out ];
	        rm -r *out*;
        end;
	    cd ../;
    end;
    if [ -f "Cargo.toml" ];
        cargo clean;
    end;
    if [ -f "Makefile" ];
        make clean;
    end;
    if [ -f "build.sbt" ];
        sbt clean;
    end;
    if [ -f "pom.xml" ];
        mvn clean;
    end;
    if [ -f "stack.yaml" ];
        stack clean --full;
    end;
    for i in *;
        if [ -d "$i" ];
            cd "$i";
            and cleanuphome;
            and cd ../;
        end;
    end;
end;
